export const ErrorCodes = {
  INVALID_BPM: "INVALID_BPM",
  INVALID_MEASURE: "INVALID_MEASURE",
  UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
  INVALID_CHECKSUM: "INVALID_CHECKSUM",
  INVALID_INSTRUMENT: "INVALID_INSTRUMENT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
